DROP TABLE IF EXISTS `pb`.`survey`;
CREATE TABLE  `pb`.`survey` (
  `id` bigint(20) unsigned NOT NULL auto_increment,
  `session_id` varchar(256) COMMENT 'web session id',
  `user_id` varchar(256) COMMENT '用户ID',
  `sex` tinyint COMMENT '性别',
  `age` int COMMENT '年龄',
  `www_expr` varchar(100) COMMENT '上网经历',
  `www_freq` varchar(100) COMMENT '上网频率',
  `prefer_ses` varchar(256) COMMENT '常用搜索引擎',
  `goal` varchar(100) COMMENT '上网搜图片目的',
  `satisfaction` tinyint COMMENT '图片搜索满意度',
  `flickr_expr` varchar(100) COMMENT 'flickr使用历史',
  `unsatisfaction` varchar(256) COMMENT '图片搜索不满意的情况',
  `pb_satis` tinyint COMMENT 'PivotBrowser图片搜索满意度',
  `pb_use` tinyint COMMENT '操作简单',
  `pb_flex` tinyint COMMENT '操作灵活',
  `pb_interest` tinyint COMMENT '功能有趣',
  `pb_easy` tinyint COMMENT '浏览方便',
  `pb_effective` tinyint COMMENT '检索有效',
  `pb_func` tinyint COMMENT '功能强大',
  `pb_final_satic` tinyint COMMENT '最终结果满意',
  `pb_tag_quality` tinyint COMMENT '标签推荐的质量',
  `pb_cluster` tinyint COMMENT '聚类效果',
  `pb_comprehension` tinyint COMMENT '聚类的描述意义',
  `pb_relevance` tinyint COMMENT '结果的相关度',
  `pb_coverage` tinyint COMMENT '结果涵盖的信息量',
  `pb_infor` tinyint COMMENT '缩略图和标签的信息量',
  `pb_more_eff` tinyint COMMENT '检索有效改进',
  `pb_hit_inconsist` tinyint COMMENT 'addressed the inconsistency problem',
  `pb_hit_disamb` tinyint COMMENT 'addressed the disambiguation problem',
  `pb_rerank` tinyint COMMENT '视觉重排有效性',
  `inputbox` varchar(256) COMMENT '对InputBox看法',
  `nav_bar` varchar(256) COMMENT 'Navigation Bar',
  `pic_box` varchar(256),
  `cluster_sidebar` varchar(256),
  `result_window` varchar(256),
  `like_best` varchar(1024) COMMENT '最喜欢的部分',
  `unlike_best` varchar(1024) COMMENT '最不喜欢的部分',
  `suggestion` varchar(4096) COMMENT '意见和建议',
  `update_time` bigint(20) unsigned NOT NULL COMMENT '更新时间',
  PRIMARY KEY  (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=gbk;

DROP TABLE IF EXISTS `pb`.`action`;
CREATE TABLE  `pb`.`action` (
  `id` bigint(20) unsigned NOT NULL auto_increment,
  `session_id` varchar(256) COMMENT 'web session id',
  `operation` varchar(256) COMMENT '行为',
  `tags` varchar(2048) COMMENT '输入tags',
  `pic_page` int COMMENT '图片翻页',
  `cluster` varchar(2048) COMMENT '点击cluster的tags',
  `visual_pic` varchar(256) COMMENT '关注的图片',
  `sort_by` tinyint COMMENT '排序, 0-随机, 1-颜色, 2-小波',
  `update_time` bigint(20) unsigned NOT NULL COMMENT '更新时间',
  PRIMARY KEY  (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=gbk;